spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /resources/**
---
server:
  port: 8888
---  
filepath: C:/Users/ShipJH/Downloads/pamsFiles 